#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

Hours=0

while [ $Hours -lt 12 ]
do
	echo "Hour: $Hours"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		(($minutes++))
	done
	(($Hours++))
done
